apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-reverse-proxy
  name: udagram-reverse-proxy
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-reverse-proxy
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: udagram-reverse-proxy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

